/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hardworking;

import java.util.Random;

public class App {



    public static void main(String[] args) {
       Title ttt=new Title();
//        System.out.println(app.title("abcd"));
//        System.out.println(app.upper("abcd"));
//        System.out.println(app.lower("ABCD"));
//        System.out.println(app.reverse("abcd"));
        System.out.println(ttt.spongebob("abCd"));
    }
}
